<a href="https://colab.research.google.com/github/Docent-1313/Python-github-wb/blob/main/4_%22%D0%9B%D0%B8%D0%BD%D0%B5%D0%B9%D0%BD%D0%B0%D1%8F_%D1%80%D0%B5%D0%B3%D1%80%D0%B5%D1%81%D1%81%D0%B8%D1%8F%22.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
import pandas as pd
from sklearn import datasets
from sklearn import linear_model
from sklearn import metrics
from sklearn.model_selection import train_test_split

In [ ]:
X, Y = datasets.fetch_california_housing(as_frame=True, return_X_y=True)
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.1, random_state=42)

In [ ]:
X_train

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude
5564,3.8372,41.0,5.265957,1.131915,1416.0,3.012766,33.91,-118.29
16016,8.0069,52.0,7.224033,1.030550,1276.0,2.598778,37.73,-122.46
17131,3.6712,30.0,3.659983,1.084568,2678.0,2.334786,37.46,-122.15
11752,3.1583,16.0,5.622378,1.034965,792.0,2.769231,38.76,-121.21
2308,4.9292,15.0,6.333333,0.988662,1411.0,3.199546,36.83,-119.75
...,...,...,...,...,...,...,...,...
11284,6.3700,35.0,6.129032,0.926267,658.0,3.032258,33.78,-117.96
11964,3.0500,33.0,6.868597,1.269488,1753.0,3.904232,34.02,-117.43
5390,2.9344,36.0,3.986717,1.079696,1756.0,3.332068,34.03,-118.38
860,5.7192,15.0,6.395349,1.067979,1777.0,3.178891,37.58,-121.96
15795,2.5755,52.0,3.402576,1.058776,2619.0,2.108696,37.77,-122.42

In [ ]:
Y_train

5564     1.564
16016    4.268
17131    3.086
11752    2.392
2308     1.094
         ...
11284    2.292
11964    0.978
5390     2.221
860      2.835
15795    3.250
Name: MedHouseVal, Length: 18576, dtype: float64

In [ ]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()
model.fit(X_train, Y_train)
print(f"Train MSE: {metrics.mean_squared_error(Y_train, model.predict(X_train)):.3}")
print(f"Test MSE: {metrics.mean_squared_error(Y_test, model.predict(X_test)):3}")

Train MSE: 0.521
Test MSE: 0.5590019245025631

In [ ]:
from sklearn.preprocessing import StandardScaler

X_scaler = StandardScaler()
X_scaler.fit(X_train)
X_train = pd.DataFrame(X_scaler.transform(X_train), columns=X_scaler.get_feature_names_out())
X_test = pd.DataFrame(X_scaler.transform(X_test), columns=X_scaler.get_feature_names_out())

In [ ]:
alphas = [0.001, 0.005, 0.01, 0.05, 0.1, 0.5, 1, 5, 10, 50]

RIdge regressoin (для того чтобы модель уравновесилась, без выбросов)

In [ ]:
best_train_mse = np.inf
best_test_mse = np.inf
best_alpha = None

for alpha in alphas:
  model = linear_model.Ridge(alpha=alpha)
  model.fit(X_train, Y_train)
  train_mse = metrics.mean_squared_error(Y_train, model.predict(X_train))
  test_mse = metrics.mean_squared_error(Y_test, model.predict(X_test))
  if test_mse < best_test_mse:
    best_train_mse = train_mse
    best_test_mse = test_mse
    best_alpha = alpha
print(f"Alpha: {best_alpha}")
print(f"Train MSE: {best_train_mse:.3}")
print(f"Test MSE {best_test_mse:.3}")

Alpha: 10
Train MSE: 0.521
Test MSE 0.559

In [ ]:
#Lasso - обнуляет веса у неважных признаков и они исчезают из модели. Из 500 признаков может оставить 5 это не приведет к переобучению и проще в расчетах и объяснению.

best_train_mse = np.inf
best_test_mse = np.inf
best_alpha = None

for alpha in alphas:
  model = linear_model.Lasso(alpha=alpha)
  model.fit(X_train, Y_train)
  train_mse = metrics.mean_squared_error(Y_train, model.predict(X_train))
  test_mse = metrics.mean_squared_error(Y_test, model.predict(X_test))
  if test_mse < best_test_mse:
    best_train_mse = train_mse
    best_test_mse = test_mse
    best_alpha = alpha

print(f"Alpha: {best_alpha}")
print(f"Train MSE: {best_train_mse:.3}")
print(f"Test MSE {best_test_mse:.3}")

Alpha: 0.001
Train MSE: 0.521
Test MSE 0.559

In [ ]:
#ElasticNet - это гибрид Ridge and Lasso
#Lasso L1(сумма модулей коэффициентов) - он обнуляет слабые признаки, делая модель проще и понятнее
#Ridge L2(сумма квадратов коэффициентов) - стабилизирует веса, особенно когда признаки сильно коллерируют

best_train_mse = np.inf
best_test_mse = np.inf
best_alpha = None

for alpha in alphas:
  model = linear_model.ElasticNet(alpha=alpha)
  model.fit(X_train, Y_train)
  train_mse = metrics.mean_squared_error(Y_train, model.predict(X_train))
  test_mse = metrics.mean_squared_error(Y_test, model.predict(X_test))
  if test_mse < best_test_mse:
    best_train_mse = train_mse
    best_test_mse = test_mse
    best_alpha = alpha

print(f"Alpha: {best_alpha}")
print(f"Train MSE: {best_train_mse:.3}")
print(f"Test MSE {best_test_mse:.3}")

Alpha: 0.001
Train MSE: 0.521
Test MSE 0.559

In [ ]:
num_features = X.shape[1]
for i in range(num_features):
  column = X.columns[i]
  X_train[f"{column}_squared"] = X_train[column] ** 2
  X_test[f"{column}_squared"] = X_test[column] ** 2
  X_train[f"{column}_cubed"] = X_train[column] ** 3
  X_test[f"{column}_cubed"] = X_test[column] ** 3
  X_train[f"{column}_log"] = np.log(10 + X_train[column])
  X_test[f"{column}_log"] = np.log(10 + X_test[column])

  for j in range(i + 1, num_features):
    other_column = X.columns[j]
    X_train[f"{column}_x_[other_column]"] = X_train[column] * X_train[other_column]
    X_test[f"{column}_x_[other_column]"] = X_test[column] * X_test[other_column]

In [ ]:
X_scaler = StandardScaler()
X_scaler.fit(X_train)
X_train = pd.DataFrame(X_scaler.transform(X_train), columns=X_scaler.get_feature_names_out())
X_test = pd.DataFrame(X_scaler.transform(X_test), columns=X_scaler.get_feature_names_out())

In [ ]:
model = LinearRegression()
model.fit(X_train, Y_train)
print(f"Train MSE: {metrics.mean_squared_error(Y_train, model.predict(X_train)):.3}")
print(f"Test MSE: {metrics.mean_squared_error(Y_test, model.predict(X_test)):3}")

Train MSE: 0.415
Test MSE: 0.44419546406068144

In [ ]:
#RIDGE после квадратов, кубов и логарифмов

best_train_mse = np.inf
best_test_mse = np.inf
best_alpha = None

for alpha in alphas:
  model = linear_model.Ridge(alpha=alpha)
  model.fit(X_train, Y_train)
  train_mse = metrics.mean_squared_error(Y_train, model.predict(X_train))
  test_mse = metrics.mean_squared_error(Y_test, model.predict(X_test))
  if test_mse < best_test_mse:
    best_train_mse = train_mse
    best_test_mse = test_mse
    best_alpha = alpha
print(f"Alpha: {best_alpha}")
print(f"Train MSE: {best_train_mse:.3}")
print(f"Test MSE {best_test_mse:.3}")

Alpha: 0.001
Train MSE: 0.418
Test MSE 0.446

In [ ]:
#Lasso - после квадратов, кубов и логарифмов
best_train_mse = np.inf
best_test_mse = np.inf
best_alpha = None

for alpha in alphas:
  model = linear_model.Lasso(alpha=alpha)
  model.fit(X_train, Y_train)
  train_mse = metrics.mean_squared_error(Y_train, model.predict(X_train))
  test_mse = metrics.mean_squared_error(Y_test, model.predict(X_test))
  if test_mse < best_test_mse:
    best_train_mse = train_mse
    best_test_mse = test_mse
    best_alpha = alpha

print(f"Alpha: {best_alpha}")
print(f"Train MSE: {best_train_mse:.3}")
print(f"Test MSE {best_test_mse:.3}")

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.397e+00, tolerance: 2.473e+00
  model = cd_fast.enet_coordinate_descent(
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.661e+01, tolerance: 2.473e+00
  model = cd_fast.enet_coordinate_descent(
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.126e+01, tolerance: 2.473e+00
  model = cd_fast.enet_coordinate_descent(

Alpha: 0.001
Train MSE: 0.44
Test MSE 0.492

In [ ]:
#ElasticNet - после квадратов, кубов и логарифмов
best_train_mse = np.inf
best_test_mse = np.inf
best_alpha = None

for alpha in alphas:
  model = linear_model.ElasticNet(alpha=alpha)
  model.fit(X_train, Y_train)
  train_mse = metrics.mean_squared_error(Y_train, model.predict(X_train))
  test_mse = metrics.mean_squared_error(Y_test, model.predict(X_test))
  if test_mse < best_test_mse:
    best_train_mse = train_mse
    best_test_mse = test_mse
    best_alpha = alpha

print(f"Alpha: {best_alpha}")
print(f"Train MSE: {best_train_mse:.3}")
print(f"Test MSE {best_test_mse:.3}")

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.164e+01, tolerance: 2.473e+00
  model = cd_fast.enet_coordinate_descent(

Alpha: 0.001
Train MSE: 0.439
Test MSE 0.491

Анализируем модели - оптимальная без регрессии.
Определяем 5 важных признаков.
Ищем пять признаков которые увеличивают цену больше всего
Ищем пять признаков которые больше всего уменьшают стоимость

In [ ]:
model = linear_model.LinearRegression()
model.fit(X_train, Y_train)
print(f"Train MSE: {metrics.mean_squared_error(Y_train, model.predict(X_train)):.3}")
print(f"Test MSE: {metrics.mean_squared_error(Y_test, model.predict(X_test)):.3}")

Train MSE: 0.415
Test MSE: 0.444

In [ ]:
model.coef_

array([ 1.69013292e+01,  1.19139240e+02,  2.90963990e+00, -3.60440361e+00,
        7.94759133e-01,  8.43316405e+00, -3.53522671e+02, -6.01638256e+01,
       -1.81816563e+00,  7.66806028e-02, -1.50347111e+01, -1.56652465e-02,
       -6.60499628e+00,  1.11660988e+00, -1.19794099e+02, -6.82253778e-03,
       -1.75494985e+00,  6.96532015e-01, -2.28121137e+00, -8.59013153e-03,
        2.89883449e+00, -1.34838080e+00,  2.40500201e+00,  1.50162559e-02,
       -3.04148528e-01,  1.56662603e-01, -6.59263633e-01, -2.44129592e-02,
       -1.13931049e+01,  6.36754523e+00, -3.17912060e+00,  4.08151380e-01,
        1.71391372e+01, -2.56469409e+00,  3.46360799e+02,  6.67774734e-01,
        2.77673176e+00, -4.39632800e-01,  6.04162496e+01])

In [ ]:
#Самые важные предикты
ind = np.argpartition(np.abs(model.coef_), -5)[-5:]
print(X_train.columns[ind].tolist())

['Longitude_log', 'HouseAge', 'HouseAge_log', 'Latitude_log', 'Latitude']

In [ ]:
#Пять самых предиктов увеличивающих стоимость
ind = np.argpartition(model.coef_, -5)[-5:]
print(X_train.columns[ind].tolist())

['MedInc', 'Latitude_squared', 'Longitude_log', 'HouseAge', 'Latitude_log']

In [ ]:
#Пять предиктов уменьшающих стоимость домов
ind = np.argpartition(model.coef_, 5) [:5]
print(X_train.columns[ind].tolist())

['Latitude', 'HouseAge_log', 'Longitude', 'MedInc_log', 'AveOccup_squared']